name: ftc-drl
channels:
  - plotly
  - defaults
  - conda-forge
dependencies:
  - alive-progress
  - numpy=1.18.5=py37h7687784_0
  - optuna
  - pandas=1.1.3=py37hb1e8313_0
  - pysimplegui>=4.32.1
  - plotly-orca>=1.3.1=1
  - python>=3.7.7
  - tensorflow-base=1.14.0=py37hc8dfbb8_0
  - tensorflow-estimator=1.14.0=py_0
  - seaborn
  - pip
  - pip:
    - cloudpickle>=1.2.1
    - matplotlib==3.3.3
    - gym>=0.15.7
    - plotly>=4.9.0
    - tensorflow==1.15.3
